# Generated by Django 3.2.6 on 2021-08-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='slug',
        ),
    ]
