# Generated by Django 3.2.6 on 2021-08-12 15:09

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('departments_app', '0002_remove_employees_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments_app.departments', verbose_name='Отдел'),
        ),
    ]
